services:
  app1:
    container_name: app1
    build: ./backend
    ports:
      - 3001:3001
    environment:
      PORT: 3001
      SERVER_NAME: "APP1"
      NODE_ENV: production
    networks:
      - nginx-network

  app2:
    container_name: app2
    build: ./backend
    ports:
      - 3002:3002
    environment:
      PORT: 3002
      SERVER_NAME: "APP2"
      NODE_ENV: production
    networks:
      - nginx-network

  app3:
    container_name: app3
    build: ./backend
    ports:
      - 3003:3003
    environment:
      PORT: 3003
      SERVER_NAME: "APP3"
      NODE_ENV: production
    networks:
      - nginx-network

  nginx:
    image: nginx:alpine3.23
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    depends_on:
      - app1
      - app2
      - app3
    volumes:
      # - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
      - ./logs:/var/log/nginx
    networks:
      - nginx-network

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx-prometheus-exporter
    depends_on:
      - nginx
    command:
      - -nginx.scrape-uri=http://nginx:8080/status
    ports:
      - "9113:9113"
    networks:
      - nginx-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - nginx-prometheus-exporter
    networks:
      - nginx-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - nginx-network

  fluentd:
    build: ./fluentd
    container_name: fluentd
    ports:
      - "24224:24224"
    command: >
      sh -c "fluentd -c /fluentd/etc/fluent.conf"
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./logs:/var/log/nginx
    depends_on:
      - nginx
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
