version: "3.9"

services:
  node-backend1:
    build: ./backend1
    expose:
      - "3001"
    environment:
      NODE_ENV: production
    networks:
      - nginx-network

  node-backend2:
    build: ./backend2
    expose:
      - "3002"
    environment:
      NODE_ENV: production
    networks:
      - nginx-network

  nginx:
    image: nginx:alpine3.23
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - node-backend1
      - node-backend2
    volumes:
      # - ./reverse-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./loadbalancer.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge