version: "3.9"

services:
  app1:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      PORT: 3001
      SERVER_NAME: "APP1"
      NODE_ENV: production
    networks:
      - nginx-network

  app2:
    build: ./backend
    ports:
      - 3002:3002
    environment:
      PORT: 3002
      SERVER_NAME: "APP2"
      NODE_ENV: production
    networks:
      - nginx-network

  app3:
    build: ./backend
    ports:
      - 3003:3003
    environment:
      PORT: 3003
      SERVER_NAME: "APP3"
      NODE_ENV: production
    networks:
      - nginx-network

  nginx:
    image: nginx:alpine3.23
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app1
      - app2
      - app3
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge