global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-prometheus-exporter:9113"]

  - job_name: "fluentd"
    static_configs:
      - targets: ["fluentd:24224"]
